// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSo2OP_Q8Xfi2RNQYUkqYQ8XfdJnwAqDs',
    appId: '1:171136651407:web:6e7bd63eaa6974ffe460fa',
    messagingSenderId: '171136651407',
    projectId: 'proyecto-portoviejo',
    authDomain: 'proyecto-portoviejo.firebaseapp.com',
    storageBucket: 'proyecto-portoviejo.appspot.com',
    measurementId: 'G-ZW0D9HR57V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgeFz1YOCEoN19KBZszYz9kR9m5iEBVt8',
    appId: '1:171136651407:android:13180548c87e147ae460fa',
    messagingSenderId: '171136651407',
    projectId: 'proyecto-portoviejo',
    storageBucket: 'proyecto-portoviejo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhiCAFB33wSVNH8wnhC4pldfYh--oxFuM',
    appId: '1:171136651407:ios:7383e6024a2dc558e460fa',
    messagingSenderId: '171136651407',
    projectId: 'proyecto-portoviejo',
    storageBucket: 'proyecto-portoviejo.appspot.com',
    iosClientId: '171136651407-6ru68hmt1rp3f0ij1ik0ibc5bu7ce4fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.antipanicoPortoviejoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhiCAFB33wSVNH8wnhC4pldfYh--oxFuM',
    appId: '1:171136651407:ios:7383e6024a2dc558e460fa',
    messagingSenderId: '171136651407',
    projectId: 'proyecto-portoviejo',
    storageBucket: 'proyecto-portoviejo.appspot.com',
    iosClientId: '171136651407-6ru68hmt1rp3f0ij1ik0ibc5bu7ce4fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.antipanicoPortoviejoFlutter',
  );
}
